src/algotest/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('algotesting.urls', namespace = "algotesting") ),
    url(r'^admin/', include(admin.site.urls)),
]

src/algotesting/urls.py
from django.conf.urls import url
from django.conf import settings
from django.views.static import serve

from . import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'test/$', views.test, name='testing'),
    url(r'about/$', views.AboutView.as_view(), name='about'),
    url(r'team/$', views.TeamView.as_view(), name='team'),
    url(r'add/$', views.AddView.as_view(), name = 'add'),
    url(r'archive/$', views.ArchiveView.as_view(), name = 'archive'),
    url(r'quick_start/$', views.quick_start, name='quick_start'),
    url(r'^datasetinfo/(?P<slug>(\w+.\w+))/$', views.DatasetInfoView.as_view(), name = 'dataset_info'),
    url(r'datasets/$', views.DatasetListView.as_view(), name = 'datasets'),
    url(r'algorithms/$', views.AlgoListView.as_view(), name = 'algorithms'),
    url(r'add_dataset/$', views.UploadDatasetFormView.as_view(), name = 'add_dataset'),
    url(r'add_algorithm/$', views.UploadAlgorithmFormView.as_view(), name = 'add_algorithm'),
    url(r'test_results/(?P<pk>\d+)/$', views.TestResult.as_view(), name='test_results'),
]

if settings.DEBUG:
    urlpatterns += [url(r'uploads/(?P<path>.*)',serve, {'document_root': settings.MEDIA_ROOT})]

src/algotesting/models.py
from django.db import models

class Algorithm(models.Model):
    filename = models.CharField(default='', max_length=20, unique=True)
    name = models.CharField(default='Some algorithm', max_length=20)
    description = models.TextField(blank=True)
    algorithm = models.FileField(default='',upload_to='algorithms/')
    train_parameters = models.FileField(blank=True, null=True, upload_to='algorithms/train_params/')

class Dataset(models.Model):
    filename = models.CharField(default='', max_length=20, unique=True)
    name = models.CharField(default='Some dataset', max_length=20)
    data = models.FileField(default= '', upload_to='datasets/')
    description = models.TextField(blank=True)
    frequency = models.CharField(default='daily', max_length= 6, choices=[('daily', 'daily'), ('minute', 'minute')])
    columns = models.CharField(default='', max_length=200)
    date_format = models.CharField(blank=True, default="", max_length=50)
    class Meta:
        ordering = ['name']

class ExperimentResult(models.Model):
    info = models.TextField(default='')
    results_path = models.CharField(default='', max_length=100)

    @models.permalink
    def get_absolute_url(self):
        return ('algotesting:test_results', [str(self.pk)])

src/algotesting/forms.py
from django import forms
from models import Dataset, Algorithm

class UploadAlgorithmFileForm(forms.ModelForm):
    class Meta:
        model = Algorithm
        fields = ['name', 'algorithm','description','train_parameters']

class QuickStartForm(forms.Form):
    base_capital = forms.FloatField(min_value= 0)
    stocks = forms.CharField()
    train_size = forms.FloatField(min_value=0.01, max_value=0.99)


class UploadDataFilesForm(forms.ModelForm):
    class Meta:
        model = Dataset
        fields = ['name','data', 'description', 'frequency', 'date_format']

class NameModelChoiceField(forms.ModelMultipleChoiceField):
    def label_from_instance(self, obj):
        return obj.name

class TestingForm(forms.Form):
    algorithm = NameModelChoiceField(queryset=Algorithm.objects)
    dataset = NameModelChoiceField(queryset=Dataset.objects)
    base_capital = forms.FloatField(min_value=0.0)
    stocks = forms.CharField()
    train_size = forms.FloatField(min_value=0.0, max_value=0.99)
    load_parameters = forms.BooleanField(required=False)
    save_parameters = forms.BooleanField(required=False)

src/algotesting/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView, DetailView, ListView, FormView, CreateView
from django.core.urlresolvers import reverse
from forms import QuickStartForm, UploadDataFilesForm, TestingForm, UploadAlgorithmFileForm
from models import Dataset, ExperimentResult, Algorithm
from code.sample import handle_algorithm_testing
import matplotlib.pyplot as plt
import os

class IndexView(TemplateView):
    template_name = "index.html"

class AboutView(TemplateView):
    template_name = "about.html"

class TeamView(TemplateView):
    template_name = "team.html"

class AddView(TemplateView):
    template_name = "add.html"

class ArchiveView(TemplateView):
    template_name = "archive.html"

class DatasetInfoView(DetailView):
    model = Dataset
    template_name = 'algotesting/dataset_page.html'
    slug_field = 'name'

class DatasetListView(ListView):
    template_name = 'algotesting/datasets.html'
    form_class = UploadDataFilesForm
    context_object_name = 'datasets'
    paginate_by = 20
    def get_queryset(self):
        return Dataset.objects.all()

    def get_context_data(self, **kwargs):
        context = super(DatasetListView, self).get_context_data(**kwargs)
        context['form'] = UploadDataFilesForm
        return context

class AlgoListView(ListView):
    template_name = 'algotesting/algorithms.html'
    form_class = UploadAlgorithmFileForm
    context_object_name = 'algorithms'
    paginate_by = 20
    def get_queryset(self):
        return Algorithm.objects.all()

    def get_context_data(self, **kwargs):
        context = super(AlgoListView, self).get_context_data(**kwargs)
        context['form'] = UploadAlgorithmFileForm
        return context

class UploadDatasetFormView(FormView):
    form_class = UploadDataFilesForm
    template_name = "algotesting/upload_dataset.html"
    def form_valid(self, form):
        d = form.save(commit=False)
        file = form.cleaned_data['data']
        d.filename = str(file)
        for file_line in file:
            d.columns = file_line[:-1]
            break
        d.save()
        return super(UploadDatasetFormView, self).form_valid(form)
    def get_success_url(self):
        return reverse('algotesting:datasets')

class UploadAlgorithmFormView(FormView):
    form_class = UploadAlgorithmFileForm
    template_name = "algotesting/upload_algorithm.html"
    def form_valid(self, form):
        d = form.save(commit=False)
        file = form.cleaned_data['algorithm']
        d.filename = str(file)
        d.save()
        return super(UploadAlgorithmFormView, self).form_valid(form)
    def get_success_url(self):
        return reverse('algotesting:algorithms')


def quick_start(request):
    if request.method == 'POST':
        form = QuickStartForm(request.POST)
        if form.is_valid():
            algorithm = Algorithm.objects.get(filename='user_defined.py')
            data = Dataset.objects.get(filename='daily1.csv')
            symbols = form.cleaned_data['stocks']
            capital = form.cleaned_data['base_capital']
            train_size = form.cleaned_data['train_size']
            params = {'algorithm':algorithm.filename, 'data_filenames': [data.filename], 'frequency':data.frequency,
                      'base_capital':capital,
                      'symbols':symbols.split(','), 'parser':data.date_format, 'train_size':train_size,
                      'load_file':'', 'save_file':''}
            result = handle_algorithm_testing(params)

            info = ''
            for key, value in params.items():
                if value:
                    if type(value) is list:
                        info += "{}:{}\n".format(key, ', '.join(map(str, value)))
                    else:
                        info += "{}:{}\n".format(key,value)
            experiment_info = info

            experiment_result = ExperimentResult(info = experiment_info,results_path = '')
            experiment_result.save()
            relative_path = 'testing/results/quick_start.pdf'
            graph_path = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(__file__))),
                                      'uploads/'+relative_path)

            result.savefig(graph_path)
            plt.close(result)

            experiment_result.results_path = relative_path
            experiment_result.save()

            return redirect(experiment_result)

    else:
        form = QuickStartForm()
        return render(request, 'algotesting/quick_start.html', {'form': form})

def test(request):
    if request.method == 'POST':
        form = TestingForm(request.POST)
        if form.is_valid():
            algorithm = form.cleaned_data['algorithm'][0]
            datasets = form.cleaned_data['dataset']
            load = form.cleaned_data['load_parameters']
            save = form.cleaned_data['save_parameters']
            load_params = ''
            save_params = ''
            print load,save
            if load and algorithm.train_parameters:
                load_params = algorithm.train_parameters.name
            if save:
                save_params = algorithm.train_parameters.name
            data_filenames = []
            for dataset in datasets:
                data_filenames.append(dataset.filename)
                frequency = dataset.frequency
                parser = dataset.date_format
            capital = form.cleaned_data['base_capital']
            symbols = form.cleaned_data['stocks']
            train_size = form.cleaned_data['train_size']
            params = {'algorithm':algorithm.filename,'data_filenames': data_filenames, 'frequency':frequency,
                      'base_capital':capital,
                      'symbols':symbols.split(','), 'parser':parser, 'train_size':train_size,
                      'load_file':load_params, 'save_file':save_params}
            result = handle_algorithm_testing(params)
            info = ''
            for key, value in params.items():
                if value:
                    if type(value) is list:
                        info += "{}:{}\n".format(key, ', '.join(map(str, value)))
                    else:
                        info += "{}:{}\n".format(key,value)
            experiment_info = info
            experiment_result = ExperimentResult(info = experiment_info,results_path = '')
            experiment_result.save()
            relative_path = 'testing/results/graph'+str(experiment_result.pk)+'.pdf'
            graph_path = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(__file__))),
                                      'uploads/'+relative_path)
            result.savefig(graph_path)
            plt.close(result)
            experiment_result.results_path = relative_path
            experiment_result.save()
            return redirect(experiment_result)
    else:
        form = TestingForm()
        return render(request, 'algotesting/test.html', {'form': form})

class TestResult(DetailView):
    model = ExperimentResult
    template_name = 'algotesting/test_results.html'

src/algotesting/templates/algotesting/algorithms.html
{% extends "index.html" %}
{% block main-content %}
<div class="row">
    <div class="col-lg-offset-1">
    <h4>Available algorithms:</h4>

    {% if algorithms %}
        <table class="table">
            <tr>
                <td>Name</td><td>Description</td>
            </tr>
            {% for algorithm in algorithms %}
                <tr>
                    <td>{{ algorithm.name }}</td>
                    <td>{{ algorithm.description }}</td>
                </tr>
            {% endfor %}
        </table>
{% endif %}
    </div>
</div>
{% endblock main-content %}

src/algotesting/templates/algotesting/dataset_base.html
<div class="dataset">
    <div class="row">
        <div class="col-lg-offset-1 col-lg-9">
            <table class="table table-striped table-bordered">
                <tr>
                <td>Dataset</td><td>{{ dataset.name }}</td>
            </tr>
            <tr>
                <td>Frequency</td><td>{{ dataset.frequency }}</td>
            </tr>
            <tr>
                <td>Features</td><td>{{ dataset.columns }}</td>
            </tr>
                {% if dataset.dateformat %}
            <tr>
                <td>Datetime format</td><td>{{ dataset.date_format }}</td>
            </tr>
                {% endif %}
        </table>
        </div>
    </div>
</div>

src/algotesting/templates/algotesting/dataset_form.html
<div class="form_base">
<form class="form-horizontal" enctype="multipart/form-data" method="post">
    {% csrf_token %}
    {% for field in form %}
    <div class="form-group">
        <div class="row">
        <div class="col col-lg-12">
            <label class="control-label">{{ field.label_tag }}</label>
            <div class="controls ">{{ field }}</div>
        </div>
        </div>
    </div>
    {% endfor %}

    <input type="submit" class = "btn btn-success" value="Add!"/>

</form>
</div>

src/algotesting/templates/algotesting/dataset_page.html
{% extends "index.html" %}
{% block main-content %}
{% include 'algotesting/dataset_base.html' %}
{% endblock main-content %}

src/algotesting/templates/algotesting/datasets.html
{% extends "index.html" %}
{% block main-content %}
<div class="row">
    <div class="col-lg-offset-1">
    <h4>Available datasets:</h4>

    {% if datasets %}
        <table class="table">
            <tr>
                <td>Name</td><td>Frequency</td><td>Features</td>
            </tr>
            {% for dataset in datasets %}
                <tr>
                    <td><a href="{% url 'algotesting:dataset_info' dataset.name %}">{{ dataset.name }}</a></td>
                    <td>{{ dataset.frequency }}</td>
                    <td>{{ dataset.columns }}</td>
                </tr>
            {% endfor %}
        </table>
{% endif %}
    </div>
</div>
{% endblock main-content %}

src/algotesting/templates/algotesting/form_base.html
<div class="form_base">
<form class="form-horizontal" enctype="multipart/form-data" method="post">
    {% csrf_token %}
    {% for field in form %}
    <div class="form-group centered">
        <div class="row">
        <div class="col col-lg-12">

            <label class="control-label">{{ field.label_tag }}</label>
            {% if field.label_tag == 'Data:' %}
            <span class="btn btn-default btn-file">
                Browse <input type="file">
            </span>
            {% else%}
                <div class="controls ">{{ field }}</div>
            {% endif %}
        </div>
        </div>
    </div>
    {% endfor %}
    {% block button %}
    {% endblock button %}
</form>
</div>

src/algotesting/templates/algotesting/quick_start.html
{% extends "index.html" %}
{% block main-content %}
<div class="container">
    <div class="row">
	    		<div class="col-lg-8 col-lg-offset-2 centered">
	    			<h2>Welcome to the quick tutorial!</h2>
	    			<p>We will test AAPL predictions on daily1.csv dataset:</p>
                    <p>Set base capital to 10000: </p>
                    <form enctype="multipart/form-data" method="post">
                        {% csrf_token %}
                        {% for field in form %}
                        <div class="form-group">
                            <label class="control-label ">{{ field.label_tag }}</label>
                            <div class="controls col-lg-offset-1 col-lg-10 centered">{{ field }}</div>
                        </div>
                        {% endfor %}
                        <br>
                        <input type="submit" class = "btn btn-success" value="Test!"/>
                    </form>
	    		</div><!-- /col-lg-8 -->
    </div>
</div>

<br><br>
{% endblock main-content %}

src/algotesting/templates/algotesting/success.html
{% extends "base.html" %}
{% block main-content %}
<p>Your dataset is successfully uploaded.</p>
{% endblock main-content %}

src/algotesting/templates/algotesting/test.html
{% extends "index.html" %}
{% block main-content %}
<div class="container">
    <div class="row">
	    		<div class="col-lg-12 centered">
	    			<h2>Welcome to frontopolar testing system!</h2>
	    			<h3>Choose data and parameters for testing:</h3>
	    		</div>
		        {% include 'algotesting/test_form.html' %}
    </div>
</div>
<br><br>
{% endblock main-content %}

src/algotesting/templates/algotesting/test_form.html
{% extends "algotesting/form_base.html" %}
{% block button %}
    <div class="row">
        <div class="col col-lg-12 centered">
            <input type="submit" class = "btn btn-success" value="Test!"/>
        </div>
    </div>
{% endblock button %}

src/algotesting/templates/algotesting/test_results.html
{% extends "index.html" %}
{% block main-content %}

<div class="row" xmlns="http://www.w3.org/1999/html">
    <div class="col col-lg-3 col-lg-offset-3 centered">
        <h3>Experiment parameters</h3>
        <div class="form-group">
            <textarea class="form-control" rows="8">{{ object.info }}</textarea>
        </div>

    </div>
    <div class="col col-lg-2 centered">
        <h3>Report</h3>
        {% load static %}
        <a class = "navbar-brand" href="{% get_media_prefix %}{{ object.results_path  }}"><i class="fa fa-bar-chart fa-3x"></i></a>
    </div>

</div>

{% endblock main-content %}

src/algotesting/templates/algotesting/upload_algorithm.html
{% extends "index.html" %}
{% block main-content %}
<div class="container">
    <div class="row">
        {% include 'algotesting/dataset_form.html' %}
    </div>
</div>
<br><br>
{% endblock main-content %}

src/algotesting/templates/algotesting/upload_dataset.html
{% extends "index.html" %}
{% block main-content %}
<div class="container">
    <div class="row">
        {% include 'algotesting/dataset_form.html' %}
    </div>
</div>
<br><br>
{% endblock main-content %}