src/algotest/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('algotesting.urls', namespace = "algotesting") ),
    url(r'^admin/', include(admin.site.urls)),
]

src/algotesting/urls.py
from django.conf.urls import url
from django.conf import settings
from django.views.static import serve

from . import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'test/$', views.test, name='testing'),
    url(r'about/$', views.AboutView.as_view(), name='about'),
    url(r'team/$', views.TeamView.as_view(), name='team'),
    url(r'add/$', views.AddView.as_view(), name = 'add'),
    url(r'archive/$', views.ArchiveView.as_view(), name = 'archive'),
    url(r'quick_start/$', views.quick_start, name='quick_start'),
    url(r'^datasetinfo/(?P<slug>(\w+.\w+))/$', views.DatasetInfoView.as_view(), name = 'dataset_info'),
    url(r'datasets/$', views.DatasetListView.as_view(), name = 'datasets'),
    url(r'algorithms/$', views.AlgoListView.as_view(), name = 'algorithms'),
    url(r'add_dataset/$', views.UploadDatasetFormView.as_view(), name = 'add_dataset'),
    url(r'add_algorithm/$', views.UploadAlgorithmFormView.as_view(), name = 'add_algorithm'),
    url(r'test_results/(?P<pk>\d+)/$', views.TestResult.as_view(), name='test_results'),
]

if settings.DEBUG:
    urlpatterns += [url(r'uploads/(?P<path>.*)',serve, {'document_root': settings.MEDIA_ROOT})]

src/templates/about.html
{% extends "index.html" %}
{% load staticfiles %}
{% block main-content %}

<div id="green">
		<div class="container">
			<div class="row">
				<div class="col-lg-5 centered">
					<img src="{% static 'algotesting/assets/img/brain_logo.png' %}" alt="">
				</div>
				<div class="col-lg-7 centered">
					<h3>О проекте:</h3>
					    <p>Мы исследуем Deep Learning в приложении к финансовым инструментам.</p>
                        <p>Мы изучаем и создаем новые алгоритмы в этой области.</p>
                        <p>Мы строим framework, в котором все это можно увидеть.</p>
				</div>
			</div>
		</div>
</div>

<div id="skills">
		<div class="container">
			<div class="row centered">
				<h3>Что реализовано:</h3>
				<div class="col-lg-3 mt">
					<canvas id="javascript" height="130" width="130"></canvas>
					<p>CNN+LTSM</p>
					<br>
					<script>
						var doughnutData = [
								{
									value: 70,
									color:"#74cfae"
								},
								{
									value : 30,
									color : "#3c3c3c"
								}
							];
							var myDoughnut = new Chart(document.getElementById("javascript").getContext("2d")).Doughnut(doughnutData);
					</script>
				</div>
				<div class="col-lg-3 mt">
					<canvas id="bootstrap" height="130" width="130"></canvas>
					<p>Дополнительные алгоритмы</p>
					<br>
					<script>
						var doughnutData = [
								{
									value: 90,
									color:"#74cfae"
								},
								{
									value : 10,
									color : "#3c3c3c"
								}
							];
							var myDoughnut = new Chart(document.getElementById("bootstrap").getContext("2d")).Doughnut(doughnutData);
					</script>
				</div>
				<div class="col-lg-3 mt">
					<canvas id="wordpress" height="130" width="130"></canvas>
					<p>Удобная библиотека</p>
					<br>
					<script>
						var doughnutData = [
								{
									value: 65,
									color:"#74cfae"
								},
								{
									value : 35,
									color : "#3c3c3c"
								}
							];
							var myDoughnut = new Chart(document.getElementById("wordpress").getContext("2d")).Doughnut(doughnutData);
					</script>
				</div>
				<div class="col-lg-3 mt">
					<canvas id="photoshop" height="130" width="130"></canvas>
					<p>Графическое приложение</p>
					<br>
					<script>
						var doughnutData = [
								{
									value: 50,
									color:"#74cfae"
								},
								{
									value : 50,
									color : "#3c3c3c"
								}
							];
							var myDoughnut = new Chart(document.getElementById("photoshop").getContext("2d")).Doughnut(doughnutData);
					</script>
				</div>
			</div><!-- /row -->
		</div><!-- /container -->
	</div><!-- /skills -->

<br><br>

{% endblock main-content %}

src/templates/add.html
{% extends "index.html" %}
{% load staticfiles %}
{% block main-content %}

<div class="container">
		<div class="row centered mt grid">
			<h2>Download</h2>
			<div class="mt"></div>
            <div class="col-lg-3"></div>
			<div class="col-lg-3">
                <a class="navbar-brand" href="{% url 'algotesting:add_dataset' %}"><i class="fa fa-table fa-4x"></i></a>
			</div>
			<div class="col-lg-3">
                <a class="navbar-brand" href="{% url 'algotesting:add_algorithm' %}"><i class="fa fa-cogs fa-4x"></i></a>
			</div>
            <div class="col-lg-3"></div>
		</div>
</div>
<br><br>
{% endblock main-content%}

src/templates/archive.html
{% extends "index.html" %}
{% load staticfiles %}
{% block main-content %}

<div class="container">
		<div class="row centered mt grid">
			<h2>Available files</h2>
			<div class="mt"></div>
            <div class="col-lg-3"></div>
			<div class="col-lg-3">
                <a class="navbar-brand" href="{% url 'algotesting:datasets' %}"><i class="fa fa-table fa-4x"></i></a>
			</div>
			<div class="col-lg-3">
                <a class="navbar-brand" href="{% url 'algotesting:algorithms' %}"><i class="fa fa-cogs fa-4x"></i></a>
			</div>
            <div class="col-lg-3"></div>
		</div>
</div>
<br><br>
{% endblock main-content%}

src/templates/index.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Frontopolar</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'algotesting/assets/css/bootstrap.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'algotesting/assets/css/main.css' %}" rel="stylesheet">
    <link href="{% static 'algotesting/assets/css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'algotesting/assets/css/font-awesome.css' %}" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="{% static 'algotesting/assets/js/chart.js' %}"></script>
      <script src="http://gregpike.net/demos/bootstrap-file-input/bootstrap.file-input.js"></script>
  </head>

  <body>

    <!-- Fixed navbar -->
    <div class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'algotesting:testing' %}"><i class="fa fa-bolt"></i></a>
          <a class="navbar-brand" href="{% url 'algotesting:archive' %}"><i class="fa fa-archive"></i></a>
          <a class="navbar-brand" href="{% url 'algotesting:add' %}"><i class="fa fa-download"></i></a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
              <li class = "active"><a href = "{% url 'algotesting:quick_start' %}">Quick Start</a></li>
               <li><a href="{% url 'algotesting:about' %}">About</a></li>
              <li><a href="{% url 'algotesting:team' %}">Team</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <br><br>
    {% block main-content %}
	<div id="hello">
	    <div class="container">
	    	<div class="row">
	    		<div class="col-lg-8 col-lg-offset-2 centered">
	    			<h1>Frontopolar</h1>
	    			<h2>Deep Learning Framework for Trading</h2>
	    		</div><!-- /col-lg-8 -->
	    	</div><!-- /row -->
	    </div> <!-- /container -->
	</div><!-- /hello -->

    {% endblock main-content %}

	<div id="f">
		<div class="container">
			<div class="row">
				<p>Crafted with <i class="fa fa-heart"></i> by DIHT MIPT</p>
			</div>
		</div>
	</div>


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static 'algotesting/assets/js/bootstrap.js' %}"></script>
  </body>
</html>

src/templates/team.html
{% extends "index.html" %}
{% load staticfiles %}
{% block main-content %}

<div class="container">
		<div class="row centered mt grid">
			<h3>Team:</h3>
			<div class="mt"></div>
			<div class="col-lg-4">
				<a href="#"><img src="{% static 'algotesting/assets/img/05.jpg' %}" alt=""></a>
			</div>
			<div class="col-lg-4">
				<a href="#"><img src="{% static 'algotesting/assets/img/02.jpg' %}" alt=""></a>
			</div>
			<div class="col-lg-4">
				<a href="#"><img src="{% static 'algotesting/assets/img/04.jpg' %}" alt=""></a>
			</div>
		</div>

		<div class="row mt centered">
			<div class="col-lg-7 col-lg-offset-1 mt">
					<p class="lead">Good words and pictures to be added later..</p>
			</div>

		</div>
</div>
<br><br>
{% endblock main-content%}